### PR TITLE
Handle dropped data correctly, with logging

### LINKED ISSUE #204: AbacoSource or AbacoGroup needs to log dropped packets
See #203 comments. We should log somewhere that a packet was dropped and filled in. Lancero source already does this. We could consider whether a more thorough, formal system for logging problems is called for.

### PR DESCRIPTION
**Pull request by joefowler**
Bahama now can drop a specified percentage of data packets. Dastard handles correctly, with logging to `~/.dastard/logs/problems.log` and log-rotation provided by the [lumberjack](https://github.com/natefinch/lumberjack) package.  Fixes #204.

Also ran `go fmt` for the first time in a while.

### CODE REVIEW

**Comment by ggggggggg** [comment]
This still doesn't set the "dropped frames" value in `DataSegment` or otherwise communicate that there was a dropped frame up to the point where it can be logged. https://github.com/usnistgov/dastard/blob/c86f1a51deba5406a16d20a15e0067e36aeb9e91/lancero_source.go#L803


I'm guessing you mean something else by "handle dropped data correctly"?

**Comment by joefowler** [comment]
Oops. I forgot to also log dropped Lancero frames. I was focused on Abaco. I'll get back to Lancero...

**Comment by ggggggggg** [comment]
Ohh I see you implemented a seperate problem logger. I don't like that solution, I think it should go into the same directory as the ljh and off files so its part of the dataset. That how I made the lancero one work.

**Comment by joefowler** [comment]
Okay, I will figure out how to use the `AnySource.HandleDataDrop` mechanism to log Abaco data drops in a fashion similar to Lancero ones.

**Review by ggggggggg — APPROVED** [review]

**Pull request merged**
