### PR TITLE
Map info to ljh3

### PR DESCRIPTION
**Pull request by ggggggggg**

### CODE REVIEW

**Comment by ggggggggg** [comment]
I was seeing an occasionaly "heatbeat missing" with simpulsesource after long periods (like overnight). I thought it could be a bug with the timing code, and tickers are easier to reason about.

**Comment by ggggggggg** [comment]
It could also be a bug in dastard commander.

**Comment by joefowler** [comment]
Would you be willing to merge the #168 (Abaco PR) before this one? Seems easier to do large than small.

**Comment by ggggggggg** [comment]
sure ill review it then merge it

**Pull request merged**
